version: '3.8'

services:
  bot:
    build: .
    container_name: shinobu-bot
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - WELCOME_MESSAGE=${WELCOME_MESSAGE}
      - GUILD_ID=${GUILD_ID}
      - BOT_COLOR=${BOT_COLOR}
      - API_BASE_URL=${API_BASE_URL}
      - ANILIST_URL=${ANILIST_URL}
    env_file:
      - .env